name: Test

on: push
# On declare des processus de travail
jobs: 
  # On donne un nom à notre job
  nodeJS: 
    runs-on: ubuntu-latest
    # On declare les taches que notre processus va executer
    steps:
      - name: Recuperation du répo
        uses: actions/checkout@v2
      - name: Installation de nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
      - run: npm run cover 
      - name: Recuperation du rapport
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./reports/**
    
 




