name: Test

on: push
env:
  APP_VERSION: 1.0.0
# On declare des processus de travail
jobs: 
  # On donne un nom à notre job
  nodeJS: 
    runs-on: ubuntu-latest
    # On declare les taches que notre processus va executer
    steps:
      - name: Recuperation du répo
        uses: actions/checkout@v2
      - name: Installation de nodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
      - run: npm run cover 
      - name: Recuperation du rapport
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./reports/**
  Build-app:
    needs: nodeJS
    runs-on: ubuntu-latest

    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation docker BuildX
        uses: docker/setup-buildx-action@v1
      - name:  Login & password docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.USERNAME_DOCKER}}
          password: ${{secrets.PASSWORD_DOCKER}}
      - name: build & push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.USERNAME_DOCKER}}/weather:$APP_VERSION
    
 




